### ISSUE TITLE
Can't install on local host

### ISSUE THREAD

**Issue by lasican1** [vangelov/calories-in#2]
Hi There is any chance to update this to the new version of all dependencies 
When i try to execue yarn start command i get an issue like below
![image](https://github.com/user-attachments/assets/eae7e43f-4352-4c65-ab65-707f0a9859bc)

![image](https://github.com/user-attachments/assets/b5dcba91-29c0-45b2-aa19-b43e4368b99d)

**Comment by vangelov** [comment]
Hello,

It seems the version of the node.js is the issue here, but I don't have the time to dig deeper. You can still run it locally if you switch to node.js 16.

Here's how to do it with `nvm` (https://github.com/nvm-sh/nvm):

- Delete the `node_modules` folder if present
- If you don't have node.js 16 install run `nvm install 16`
- Switch to node.js 16: `nvm use 16`
- Run: `yarn install`
- Run :`yarn start`

**Comment by lasican1** [comment]
Thanks! It works :)
